### PR TITLE
[add] place blog backup in branch `backup`, make git log clear

### PR DESCRIPTION
**Pull request by HuJJ-NB**
I think this will works well.

### CODE REVIEW

**Comment by yihong0618** [comment]
seems you delete all my `md` files

**Comment by HuJJ-NB** [comment]
it will save in branch `backup`, and commit `update blog xxx` in this branch, branch `master` just have `README.md` and `feed.xml`.

**Comment by HuJJ-NB** [comment]
it will save in branch `backup`, and commit `update blog xxx` in this branch, branch `master` just have `README.md` and `feed.xml`.

if you worry about your `md` files, you can move your `md` files first.

**Comment by yihong0618** [comment]
@HuJJ-NB will take a look this weekend maybe./

**Comment by yihong0618** [comment]
can you only change the `main.py` and open a separate `PR`.
its better
- do not delete files
- do not delete .gitignore
-

**Pull request closed without merging**
